name: Push and Deploy Serverless function
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'main.py'
      - 'requirements.txt'
      - 'templates/**'
      - '.github/workflows/deploy-ycf.yml'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: yc-actions/yc-sls-function@v4
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_DEPLOYER }}
        folder-id: ${{ vars.YC_FOLDER_ID }}
        function-name: 'ru-proxy'
        runtime: 'python312'
        memory: '256Mb'
        execution-timeout: '180'
        service-account: ${{ secrets.YC_SA_ID }}
        entrypoint: 'main.telegram_webhook'
        environment: |
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          YC_FOLDER_ID=${{ vars.YC_FOLDER_ID }}
          TELEGRAM_CHAT_WHITELIST=${{ vars.TELEGRAM_CHAT_WHITELIST }}
        include: |
          main.py
          requirements.txt
          ./src
          ./templates
