name: Terraform via Webhook

on:
  repository_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
      TF_VAR_iam_token: ${{ secrets.YC_IAM_TOKEN }}
      TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
      TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="preemptible=true" -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
